language: android
sudo: false
cache:
  directories:
  - "$HOME/travis/.rvm/"
  - "$HOME/Library/Caches/Homebrew"
  - "$HOME/travis/.gradle/"
branches:
  only:
  - master
android:
  components:
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - extra-android-support
notifications:
  slack:
    secure: qHqIcGXhqUrprDck/cVKCBs0U6FQxtHVBsjF37bR/+AwohrWUnnoKLRN5BWg1q9TV91ADFbyWZDiSGDv+PZELGJalIL6i9NFvph5goJVG1kgnuHwwGCdcbLwy2rV7ShsWbXClC2iT+KXLTzmcUKYYaDvP5l/VOEiIQImQs4ErItoM3TvelRMLZVyhKQN5aT+tF86SkooFX2Lis/2p7mdNIhmHrNtnzd45424Ocu8lrAYUrSM2crskKp7wVhk7ycK1bMQMrmkWmrDrTWdGIyf7Vi/uGCBdeFp/3bR/zLAebTFibUw2IJG12FyF+F5MEgQHTnnHRNEn97wjcJRHI78U9Q4W/n3yxIEsZXx7wCPb/LQ3JNI3ooVioYq+0SUvLcPPcf16B++BDueBqyQ4v65PDA2+qHLW86GwiNOouleP7VtTPucXmo5dDKnWNdiysqN8paBUfnbdxuRIcw3ZMGro46Ckm6xIUuqVQXuPUQujdOcSnsna4AyGF1ldmToUiPC/i377sBg3av42iULAUrJIAIfKJZA6BbtEkIYEAJNYOIEZmPjEQJP0mI3OhY6sh3P4m0o5jyEvNRZmYejzGDpNWQkuFGLCaooYgE6mmNs9pZAhgaQ5WwjBwGBbhbY0rikjQkO5G9NDU50g0XycD3DLMCOj11XdkGEtsFzGlD1tzs=
before_install:
- openssl aes-256-cbc -K $encrypted_27ddda8dd36c_key -iv $encrypted_27ddda8dd36c_iv
  -in crosscourse.jks.enc -out crosscourse.jks -d
- make travis-init
script: make travis
before_deploy: make travis-deploy
deploy:
- provider: releases
  api_key:
    secure: lNOYIF0IXGIToG4qzPtWKRdEzj85S0+KxahWSZimJ2FitpbYjCMLk9H20zghKd6JlGteSG51i974wxGDzBkcAWVP1/CidmwJBgd6tKufk+/HKPTknMCVUv9pCYYx4VZDbKJq5/TLs8SXbnMTgYw1tzBZm2BAHrkkswy0QO8qDGNyqZJO7CDbs1LxqWrvV4RnjBknftJEiyg21I0TBmKRppZEC/BiNUAnJSLeJCz+ruUD+wtgzeBIYHLhucL8zqfxoXWvXEY8jhNPFs17B+p1P+GiAhYSBvUccine3hvP9cwXUumxOaTr0qPU9Dansuaa0xNeruRd2r3srB369Z03YMijiTxKDIrg7KRZj/SFQxFBWr7sHRvcDmHk1dQ4ovSa1+fdJ9pbukvxpCZNMlXo2vDjmf4L1gnO8H53NW3A7zKHDNuTmPoEvgAxo8sP2TcBSVl9BQfMVh30JHKU+5PkwaJgmwEAq59CJbbPc0dfTw63q/vXwG2Nx3t2oJwRK2l2bv6KSoyyNnNjiIrsg5rHh0plm0pG5RgQRxBT4E4fk9X2/S3c1Zp4waQAgIH9vlhmOhq7x/4RGASd9hOPvSAFhe9ek2zPgD4YuwWdnI5Tq70Mk/5qbCYddK0DR+wteVWpE6fqqDwW/OBoMun/RA2ySIjkPV+0uqUa6XeECSeSYq8=
  file: app/build/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    repo: ArcBlock/arcblock-android-sdk
    branch: master
- provider: s3
  access_key_id: AKIAJMQME6TJ4NT6BJ7A
  secret_access_key:
    secure: KSH3iXfRizsNLuWdFjo+vRiY7qKJAAkOheX/N5Mcp1oUBoSXQURYmFM6+xQJwOpUntWn3jWdqICSOA7/iVgsfk6f4WPo1Z6Nwlb/8JpPpVlrjz3F12J4+1s1NDX8zVWSxgqVaiIXCJ+Gq7wYvhbd0Wr12GXQLbACc25q1biZlA/HBCeA5t9cH/rVqzRdPJ6n1U6wjsAqSGV9pb1xdORy0s95z8gvNvhVzydaXVUOS9HICWk8f8CzFOYmaFmEFVXoV05KAE9v2YzBw06pjSNdIIHWDUZohndYfHf1k73S+f2viw6N6SMmz2B5BgWTPGUzKbj/Sa7SvyMCjCHsiashjDRzOdXlZSvK09XM1VLmSq39AFc0fyOJAZNV7W5FBI6+kzK0NyTzOHxHVY2oGWeWsREwapI13KW0v68IbIEsAIU0LDhxPcFs+TKkF4RPVBqQog7/rSZDrDhgxDNo3ES1ijQf51E5Q4y4nh+rojyIZ+r5y+W0IemPW5LkzvaX51pau7U5+7bgD1svoB6meXoBVpQ9yU/f/QhrRYolcqdGBfzLHuo/DzMnM83ZrMY1ZSroRhyRIOpcuQnNDyMuW4pECV1jXLFHH99CcHtZnVpZ+hydmR06WuYvY20RNBbn5+5sDx/17jK65/9feCUX0irMzdENleILfmohv3ykJ1uig4g=
  bucket: android-docs.arcblock.io
  local-dir: docs
  skip_cleanup: true
  region: us-west-2
  on:
    repo: ArcBlock/arcblock-android-sdk
    branch: master
after_deploy:
- fir p app/build/outputs/apk/release/app-release.apk -T $FIR_TOKEN -c "`git cat-file
  tag $TRAVIS_TAG`"
env:
  global:
  - secure: eeQdwXxWaaxIegGKl4ASghHEF4ID+12BLI5d1wqImXo0XiDtmtn0NjXqRGrhrL6Laljc5l5QjFrCJXYPDGk9v5uDo55g+8Qh9HE7U4DtLw4Xtq2213JRBDfziuoVocc6nbVgweEWJgEVriZoinjIMUXIqXHVCWBJPJL1j2+trrnGyQIBinHpiFEdDeO6y5zPQ8yskN7fUJpidy9TXJ5zucq3H/Y+O400/v0NozAcKqbus22eaiNKYJMmx/CqkdDeg6SR2wVdw6wi4Qw18klFHlRBxYIUcEakCGut4rJowVrdf9QnkaVOz1uatiTswzCCUGWQ6IPAt+VbRgd/vIBoQMZBjK0XJgxcSlqBUfyon9v7BnqbnbF6nq5r911XDcET9w2x8d4lZ4jBM5x0NAbhPvA7jDJcjNUeWcAHXc8Ldy38ejBYtqmTRO1hrI2b25R0Zp9mSf4ahdsq+qSlf0bLnrbBu0HfRkzcGpMJAA+KlzUUDpiS1j9uQhz+9mAg4xsdXz2nVQd7aEOAWtKFIMZG9ZuFv1CYf22BZ1lpEayP6AvotEXTzloGCA1MyWU4hXJjJx2whIHN696Y9nHiaX9dqs5f5W4RQ9lb34BJttTcMkdcq8bpeIFlTniCkRTt4XDmp0Yw2BNofCd+uViupvj0Y0+js6nPjZjDya6jmPAEgHY=
  - secure: k4jdFnFv/XYQsdY7Wz8G4lH+JdOn3OJc7Mn2gWITb5L5IeamNpM7oMgtpvtahzNL8j0RKn6AfN7/Vt0m5ty2GweTcEO7Pwq45SBQqf/LIRFZbMGgXDuAWL5fA2oaTbAuVFJeu21J+gQc2SsTy/R4iauE72RkxAaanjdwWpIj13v0oqmxOp1ecZaL61xRfzF0IheQF/lLj5d0UPOXBVoDs01iUXY4UhIlBH6YRlkd1EBgOIVZyZgWy/TmHX6ohmgM5f+KuHHIS3TMqogT1Ps7e6sF+BhckZFSEpwgBE63mHn3sI4iR8lvQUkEQsCAaASwPhr3XynYb4aHp9WMlvTFsCt+dsWsQAMKTXfYjnKXSDZEUbhI7EQ/2aqLSwopHGHNY5PApg7eNmV7euijP3sdtma3ecq3nhm4GXwLf0r725o5BdMNLxJsdt8pZOX/A/sunp7xhP4bjxa5lIjIEji0sOHnf1FC5qQbNbbgCJWEsz/xtAsMVNzB0HcvUf4DOrj2kPLci7Z36hArJ7YK4T+rxDg7b3pe5NOdVHgOIwsSevjCnhPJWdgOzDP5wvZi9FOv74wakrnwaEQH18WRsOtqrNQRgiFnPgvs9RSuw70YRI/XHALIY6eE870OQjPfbY2vjwX+Ao2V/MdG7H7+PQ2hjt+5Fx53B2eqRLTnR2bWBGQ=
  - secure: M+cvTzSCqUjlOauf851G7iXE5/gM9RF1rcZQGzg7XITwIT73G5qpgMmx/DaYb/yY8YR2jJZGu7iSQ1o/6UpFl6amVmYLmYb4PgvZAtGrt8Ufn830b5vOmMriLp4obp6mOxjzlFriasQMQBTCsnqujGdZqOGiFJj6yjQMzkbe8+MZQ10bpalizeKCeHdemqi+Y4Sd9KPKubbOc+0LgHQDW3Js/ZeBjhndQGfh0o8EFvcX+OLWJbYODt/2UEakje7/ig3d/E+mFtshKaGey/vdS/NbOKD4eqCRr2DvqQIBwqedAQxPCC70aFjsPbKM0wIMML3OwPltzHbBptgvW065f2KKgvZt4iYgIERjJdK4RxhlSifd6ucNehKzBYskZjx7V3I6HPkwigRtsU1gI114t04tDjfHYI3pdDzlloiL3FYJ3kT/Bheyam7gpLGYAKrFcmd6DEzuWWKvOIulUcEbp/XtQLJKduLKNENRwz5HAVL21FdlsxMBnmAOQS8+0JXloLBrdz9kUk0NvcC33pfO2o5Dixgk4PxprHCNfgxP8jTR22W9NSEVeC5Pax9Mu7d7+C3PRfguR5djL2ZjFV6/uAI3s0YQL+4sgv6GDhUv3QXD1ipleF/GTxyKQvvEdCfkG0e8QID6TFnpQDa7OVPskGQjVrrLZCz2CjFtnM9GYcU=
  - secure: bk+GoN0xRihqfpI6hIYpO8UK9ULz99u1ju1R5XP3zGpQte/YZCTkoZfSbqb4vPThJvRNeaGRgK8xWatY8Y9wozUIREtWtEd82zuA+gH+sAWn945vFbSA2yJzWz/BfC08b8chV13S1nBONQqVWH6f8b5uHk3GSZCjLceYFssbRsYnQVkDuG2b0qeeKdG9GLYPwPmONgG7VECRUXmUz3sbKy20ohIF1VqiTuv6+dubOHKg9BEw5wsmfKErsaK76nup+e0jt9qP1/sfesaLd4I6ZMmYh+zmeAcb9tQi17iUz3okQaNWtwcXKAhSe7kQuEAABpd9ToN7WY/cyzpL5sFfIx4Zw6UFtTztGD++qbIAYl6miqBvOgNWlBDXXhS2yP5Jv1Kihmb1KlbKXkZsqPkzLYji+cGKIyCNfT+218kuoHPbD8sui0/CCOiXyMe/r288QUF5mQQ7uLmLLZODILEoE3xIULw52RerSjx/oil6oA18iEMqMxGVQ2EomUjRGkVxfvJDnD66ZueFYRiheJF3ALPeQXVatZzbTiWDZSqm9lmeqWkd0QMzHKT/VK9XBmOmGsvkDAjSe5ZP05oHPaNfMWceWrR4OW8RrHjNyNOqavl/VR1h+SWR3utW7dHWsh6Rcu5scEWMoRTVR1WAKWPGx4j+C+92hpBfzx3EnI0ZuQE=
v35W6Nx5ckK6UvILiUwTj1JaY1pd1ZaGlUOz3jEp:
  secure: CoWMsFYs3dVTomb21vR869Nf9e4ozXmicY6HogXD8Aine+B1UP1Y2a+wGGhGed3i1+yIjr5cJtJ8Rg0k3OmP43bnNiQIO91+qWGXzfT/i+eN9Dju3ZtWPqcf+wkMJHXXdZpOk3gtLCDULMMMEOhzRbAtbIW9naSoKQv3OEsUjhT5gfGM0mnkd4Z8ZTaWAwyGcUIjIzIOdshh51VLL+ofmxNt2MiHx2WAos3zjNk4FjJPegEDD+aRIE5S25eeelYuk+ZFc/y07ysXG8T+/HjOu79/JIr9AQZD/AKR+yI0/ZiSpu32zvAao0bibLj3lYQpXDtXy8gAZfxfPbA961yGKz/gSjckaEAHl59dWWXQPo9rGWnoNIfOtqjT0T3GVRwh+BtX2scY/3npnCqSSFXm+vfdQUHHkkHCbPUD2wpnxtCnrl6Wk9GrvUI0Sf+tyxxM7sb8qmnGD0DNYZcWJl1im0PQzCTjeUMwZoDq4HjTBYb34PbueEt9bNZ9Fm+UuFIC/L+NmAb+cvRO5Otz6fn8EYYODFsgISlsPSxfkegf7AGuGnQIbHoO6crAy3163llOrr1ebtwlLRq5QKCDon7P0FlRSzvMrpZQEB25/IzX/idO4QM/mQi5BhN5R2zUzSCrKODSBTe5Dd1Sz2TlxHc4e5jD/R1smts7e/q9Qg3mPR8=
